# Generated by Django 3.2.6 on 2021-08-18 12:44

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('emails', '0001_initial'), ('emails', '0002_rename_email_followupemailstemplate_email'), ('emails', '0003_contact'), ('emails', '0004_auto_20210805_1729'), ('emails', '0005_alter_contact_email'), ('emails', '0006_auto_20210805_2227'), ('emails', '0007_auto_20210805_2235'), ('emails', '0008_alter_sentmail_contact'), ('emails', '0009_alter_sentmail_contact'), ('emails', '0010_alter_followupemailstemplate_index'), ('emails', '0011_alter_sentmail_template'), ('emails', '0012_sentmail_sent'), ('emails', '0013_sentmail_available_to_send'), ('emails', '0014_alter_sentmail_available_to_send'), ('emails', '0015_alter_sentmail_available_to_send'), ('emails', '0016_alter_sentmail_generated_text'), ('emails', '0017_remove_sentmail_is_active'), ('emails', '0018_sentmail_sent_date'), ('emails', '0019_auto_20210813_0103'), ('emails', '0020_alter_sentmail_generated_subject'), ('emails', '0021_alter_followupemailstemplate_subject')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('client', models.CharField(blank=True, default='', max_length=512)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('region', models.CharField(blank=True, default='', max_length=512)),
                ('country', models.CharField(blank=True, default='', max_length=512)),
                ('contact', models.CharField(blank=True, default='', max_length=512)),
                ('company', models.CharField(blank=True, default='', max_length=512)),
                ('location', models.CharField(blank=True, default='', max_length=512)),
                ('achivment', models.CharField(blank=True, default='', max_length=512)),
                ('in_comunication', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpEmailsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('index', models.IntegerField(help_text='min: 1', unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('email', ckeditor.fields.RichTextField(help_text='You can use: {{client}}, {{email}}, {{region}}, {{country}}, {{contact}}, {{company}}, {{location}}, {{achivment}}')),
                ('days_after_prev', models.IntegerField(default=0)),
                ('subject', models.CharField(help_text='You can use: {{client}}, {{email}}, {{region}}, {{country}}, {{contact}}, {{company}}, {{location}}, {{achivment}}', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SentMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('generated_text', ckeditor.fields.RichTextField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_mails', to='emails.contact')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_mails', to='emails.followupemailstemplate')),
                ('sent', models.BooleanField(default=False)),
                ('available_to_send', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('generated_subject', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
    ]
