version: "3.9"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "54321:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=followup
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    image: webapp
    command: [ "sh","-c","python manage.py migrate && uwsgi --ini uwsgi/uwsgi-docker.ini"]
    # command: [ "sh","-c","ls"]
    # command: python manage.py runserver 0.0.0.0:8000
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - db
